service: mcp-server

plugins:
- serverless-python-requirements

provider:
  name: aws
  runtime: python3.10

functions:
  main:
    handler: main.main
    events:
    - http: ANY /
    - http: 'ANY {proxy+}'
